name: Build and Push Images

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch: { }

jobs:
  kube-trigger:
    name: Release kube-trigger Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go Caches
        uses: actions/cache@v3
        with:
          path: |
            .go/gomodcache
            .go/gocache
          key: ${{ runner.os }}-gobuildcontainer-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gobuildcontainer-

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Show Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Show Make Variables
        run: make trigger-variables

      - name: Build and Push Images
        run: make trigger-all-container-build-push

  manager:
    name: Release manager Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go Caches
        uses: actions/cache@v3
        with:
          path: |
            .go/gomodcache
            .go/gocache
          key: ${{ runner.os }}-gobuildcontainer-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gobuildcontainer-

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Show Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Show Make Variables
        run: make manager-variables

      - name: Build and Push Images
        run: make manager-all-container-build-push
