name: Release kube-trigger Binaries

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: { }

permissions:
  contents: write

env:
  GO_VERSION: '1.19'

jobs:
  kube-trigger:
    name: Release kube-trigger Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Setup Go Caches
        uses: actions/cache@v3
        with:
          path: |
            bin/gomodcache
            bin/gocache
          key: ${{ runner.os }}-gobuildcontainer-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gobuildcontainer-

      - name: Show Make Variables
        run: make trigger-variables

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(make trigger-version)
          echo ::set-output name=VERSION::${VERSION}

      - name: Build Binaries for All Platforms
        run: make trigger-all-build

      - name: Attach Binaries to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          prerelease: ${{ contains(steps.get_version.outputs.VERSION, 'alpha') || contains(steps.get_version.outputs.VERSION, 'beta') }}
          files: |
            bin/kube-trigger-${{ steps.get_version.outputs.VERSION }}/kube-trigger-*.zip
            bin/kube-trigger-${{ steps.get_version.outputs.VERSION }}/kube-trigger-*.tar.gz
            bin/kube-trigger-${{ steps.get_version.outputs.VERSION }}/*-checksums.txt
