name: Build and Push Images

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch: { }

jobs:
  kube-trigger:
    name: Release kube-trigger Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Show Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Show Make Variables
        run: ./hack/make-kt.sh variables

      - name: Build and Push Images
        run: ./hack/make-kt.sh all-docker-build-push

  manager:
    name: Release manager Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Show Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Show Make Variables
        run: ./hack/make-mgr.sh variables

      - name: Build and Push Images
        run: ./hack/make-mgr.sh all-docker-build-push
