name: Upload Test Binaries

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch: { }

env:
  GOLANGCI_VERSION: 'v1.47.2'
  GO_VERSION: '1.19'

jobs:
  detect-noop:
    name: Detect No-op Changes
    runs-on: ubuntu-latest
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.mdx", "**.png", "**.jpg", "**.svg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false

  upload-test-binary:
    name: Build and Upload Test Binaries
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux-amd64
          - darwin-amd64
          - darwin-arm64
        binary:
          - kube-trigger
          - manager
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Setup Go Caches
        uses: actions/cache@v3
        with:
          path: |
            bin/gomodcache
            bin/gocache
          key: ${{ runner.os }}-gobuildcontainer-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gobuildcontainer-

      - name: Run Go Generate
        run: make generate

      - name: Show Make Variables
        run: ./hack/make-kt.sh variables

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(./hack/make-kt.sh version)
          echo ::set-output name=VERSION::${VERSION}

      - name: Build Binary
        env:
          DIRTY_BUILD: true
        run: |
          PLATFORM=${{ matrix.platform }}
          BINARY=${{ matrix.binary }}
          make -f ${BINARY/-/}.mk build-${PLATFORM/-/_}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.binary }}-${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}
          path: bin/${{ matrix.binary }}-${{ steps.get_version.outputs.VERSION }}/${{ matrix.binary }}-*-${{ matrix.platform }}
